### PR TITLE
fix: update CI/CD process to enable auto-release workflow

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- add new hook to pre-commit to fix eof lines
- add new `release.yml` workflow. this workflow will automatically:
	- create and push new tag for next [semver based on conventional-commits](https://github.com/semantic-release/semantic-release#commit-message-format)
	- create GitHub release with notes
	- update Changelog with release notes
	- this workflow will also automatically notify PRs that are included in the release, mimicking the manual behavior but now its automated https://github.com/clowdhaus/terraform-aws-rds/pull/1#issuecomment-952097291
- remove old `chglog` configs and Makefile

## Motivation and Context
- automate release process in a standardized manner
- standardize new CI workflow (copying from RDS Aurora)
- Closes #3 

## Breaking Changes
- No

## How Has This Been Tested?
- [x] https://github.com/terraform-aws-modules/terraform-aws-rds/pull/361

### CODE REVIEW

**Comment by antonbabenko** [comment]
This PR is included in version 0.2.1 :tada:

**Comment by antonbabenko** [comment]
This is an ancient module.

I am not sure we even need to have it since most of the logic is available as part of AWS provider natively for a rather long time. What do you think?

/cc @daroga0002 @bryantbiggs

**Comment by daroga0002** [comment]
as per me it can be retired, looking also into terraform registry it doesnt looks used by community too much comparing to other modules

**Comment by bryantbiggs** [comment]
ya I figured it was along the same lines as the s3-object module. I'm in agreement as well, lets archive it 👍🏽

**Comment by antonbabenko** [comment]
Final release before archiving it - https://github.com/terraform-aws-modules/terraform-aws-ebs-optimized/releases/tag/v0.2.1

**Pull request merged**
